### ISSUE TITLE
[REVIEW] Is scale argument necessary on radial_spectrum?

### ISSUE THREAD

**Issue by santisoler** [brmather/pycurious#18]
Part of https://github.com/openjournals/joss-reviews/issues/1544.

I'm a little bit confused about the `scale` argument of `CurieGrid.radial_spectrum`:
https://github.com/brmather/pycurious/blob/759fc520c22503f0b40b6a63faa4e632dd9f1e88/pycurious/grid.py#L190

Is it only used for units conversion? If that's the case, it's not a good choice to let users to change unit conversions constants.

By the way, is there a special reason why converting units from meters (grid coordinates) to km (wavenumbers and estimated depths)?

**Comment by brmather** [comment]
Yes you are correct, the only point of this is to change metres into kilometres. That's because both Tanaka and Bouligand estimate Curie depth with the wavenumber in units of radians per km. Mainly I just keep that scale parameter in there to flag to users that they should carefully consider the units they work in. However, if you think this argument can be removed in place of more explicit instructions in the docstring, then I'm happy to do that.

**Comment by santisoler** [comment]
Ok. I would remove the `scale` argument. It shouldn't be modifiable by the user because it's a factor used on unit conversions. It's always better to let users change units outside functions instead of passing a factor to do so (that's a big source of errors).

Although I'm more inclined to standardize the use of units (I always prefer using SI units unless it's strictly necessary - e.g. use of mGal in gravity or nT in magnetism), I understand why you would prefer using km on the depths. Nevertheless, whenever you are returning not standard units, I would add a big warning on the docstring of the function, and implicit its units on the `Returns` section.

**Comment by brmather** [comment]
In general I agree and try to follow SI units wherever possible, however, the ubiquity of rad/km in the case of computing Curie depth has forced my hand in this case. Otherwise the `bouligand2009` or `tanaka1999` functions can not directly accept the output from `radial_spectrum` without an intermittent step of converting units. I predict this additional layer of complexity would be a source of error (and perhaps increase the number of GitHub issues!)

I have improved the documentation to clarify the conversion from m to km and removed the `scale` argument c2e545e5c9a2420ae90d126846c08c3bbc2422f6.
